### ISSUE TITLE
Silent failure with latest esp-idf and mbedtls

### ISSUE THREAD

**Issue by negativekelvin** [warmcat/lws-esp32-test-server-demos#13]
Building against https://github.com/paulreimer/mbedtls/tree/new-esp-idf and the latest esp-idf with a few tiny tweaks to lws include paths compiles and runs but does not process client connections (client side timeout) and there are no errors in log output.  The only sign of client connect is a decrease in free heap.  Could be due to changes in idf select behavior or mbedtls changes.  Just wondering if anyone has looked at it.

**Comment by negativekelvin** [comment]
Yes it was due to the select behavior, removing LWIP_SOCKET_OFFSET from all the FD_SET and FD_ISSET calls in lws-plat-esp32.c fixed it.  

Hopefully the new esp-idf will fix the station loses connection after extended time bug.

**Comment by negativekelvin** [comment]
Good news, the station hasn't dropped off the network since updating esp-idf so it is a critical update.  Do you want PRs?

**Comment by lws-team** [comment]
Yeah, it will be a mice help thanks.
