### ISSUE TITLE
Submodule update problem

### ISSUE THREAD

**Issue by HanVertegaal** [warmcat/lws-esp32-test-server-demos#7]
When I clone the repository (Nov 24) and then try to update the submodules I get the following:

`lws-esp32-test-server-demos (master *=) $ git submodule update --init --recursive
fatal: reference is not a tree: 9c7eed17ff370f543c93f6127e8467bde4a6727d
Unable to checkout '9c7eed17ff370f543c93f6127e8467bde4a6727d' in submodule path 'components/libwebsockets'`

**Comment by lws-team** [comment]
Yes... I pushed updates today on -factory and -test-server-demos that work againt HEAD esp-idf... the version of lws they use as subprojects is updated as well,

If you update against the new versions it will find the correct lws commit.

**Comment by HanVertegaal** [comment]
It works now. Thank you.
